export const EQUIPMENT_PREVIEW_ITEMS = [
  {
    id: 'preview-m-101',
    managementNo: 'M-101',
    category1: '저류조',
    category2: '저류시설',
    category3: '기계',
    category4: '저류조기계저류시설',
    name: '통합방류조 유량조절수문',
    model: '일체형 MOP',
    specification: '전동 버터플라이 수문',
    unit: '대',
    quantity: 1,
    power: '2.2 kW',
    installedAt: '2020-10',
    vendor: '(주)신정기공',
    location: '통합방류조',
    accessory: '일체형 MOP',
    status: '사용 중',
  },
  {
    id: 'preview-m-203',
    managementNo: 'M-203',
    category1: '저류조',
    category2: '저류시설',
    category3: '기계',
    category4: '저류조기계저류시설',
    name: '하수이송펌프',
    model: '수중펌프',
        specification: '30 m3/h',
    unit: '대',
    quantity: 5,
    power: '30 kW',
    installedAt: '2020-10',
    vendor: '(주)동원파워펌프',
    location: '저류조',
    accessory: '',
    status: '사용 중',
  },
  {
    id: 'preview-m-204',
    managementNo: 'M-204',
    category1: '저류조',
    category2: '저류시설',
    category3: '기계',
    category4: '저류조기계저류시설',
    name: '하수이송펌프 토출밸브',
    model: '전동 버터플라이 밸브',
        specification: '250A x 7.5 kg/cm2',
    unit: '대',
    quantity: 5,
    power: '0.75 kW',
    installedAt: '2020-10',
    vendor: '(주)신정기공',
    location: '저류조',
    accessory: '일체형 MOP',
    status: '사용 중',
  },
  {
    id: 'preview-lt-202',
    managementNo: 'LT-202',
    category1: '저류조',
    category2: '저류시설',
    category3: '계측기',
    category4: '저류조계측기저류시설',
    name: '하수저류조 #1 수위계',
    model: '초음파 수위계',
    specification: '0~10m',
    unit: '대',
    quantity: 1,
    power: '-',
    installedAt: '2020-10',
    vendor: '(주)리테크',
    location: '하수저류조 #1',
    accessory: '',
    status: '사용 중',
  },
  {
    id: 'preview-el-1',
    managementNo: 'EL-1',
    category1: '저류조',
    category2: '저류시설',
    category3: '전기',
    category4: '저류조전기저류시설',
    name: 'UPS',
    model: '무정전 전원장치',
    specification: '',
    unit: '대',
    quantity: 1,
    power: '-',
    installedAt: '2020-04',
    vendor: '그린파워테크놀로지',
    location: '전기실',
    accessory: '',
    status: '사용 중',
  },
];

export const EQUIPMENT_HISTORY_PREVIEW = [
  {
    id: 'history-1',
    equipmentId: 'preview-m-204',
    date: '2020-07-16',
    completedAt: '2020-07-17',
    type: '위탁',
    content: '냉매 가스 주입',
    company: '캐리어에어컨',
    contact: '010-3862-0547',
    price: 150000,
    source: '장비이력',
    photoCount: 0,
  },
  {
    id: 'history-2',
    equipmentId: 'preview-m-204',
    date: '2020-05-10',
    completedAt: '2020-07-03',
    type: '위탁',
    content: '에어컨 일체 교체',
    company: '캐리어에어컨',
    contact: '010-3862-0547',
    price: 2190000,
    source: '업무사진관리',
    photoCount: 4,
  },
];
